pysathq/pysat

cardenc/pycard.cc
Got the following error while creating multiple SAT instances "Fatal Python error: deallocating None" and fixed it.
https://stackoverflow.com/questions/15287590/why-should-py-increfpy-none-be-required-before-returning-py-none-in-c
=> bugfix: Fatal Python error: deallocating None

examples/lbx.py, examples/lsu.py
In Minicard's repository test folder (https://github.com/liffiton/minicard/tree/master/tests/in), WCNF+ instances have the extension ".wcnfp". Fixed LBX's WCNF+ support in order to accept files with this extension.
Also, a 'solver_name' was being passed to LBXPlus, causing an error. Fixed this too.
I removed solution-based phase saving from LSU because what was implemented is not true solution-based phase saving as implemented in LinSBPS.
=> added WCNF+ support to LSU; fixed WCNF+ support in LBX

examples/lsu.py, pysat/solvers.py, solvers/pysolvers.cc
Interrupt support is useful for setting timeouts.
This change requires releasing the GIL in the solve_limited functions before passing control to the actual SAT solver. Therefore, solve_limited is no longer thread safe, but the user shouldn't call a SAT solver's methods (except for interrupt) from a different thread while in the middle of a solve_limited call anyway.
=> Added interrupt support to SAT solvers and LSU

pysat/formula.py
Hard clauses were getting a weight of 0 when dumped to a .wcnf file through the to_file method. The top weight value wasn't being updated when a soft clause was added using append.
=> WCNF and WCNFPlus to_file bug fix

pysat/formula.py, requirements.txt, setup.py
Addresses issue #21.
Marked as draft until some more details are worked out such as:
1. What is the best way to test. The code seems to produce the same results as the docstring example suggests it should.
2. What is the best way to force the outputs to be true? An `aiger.BoolExpr` encodes a predicate. I would like to be able to simple send this expression into `pysat` and find solutions that make this predicate True.
=> Depend on py-aiger-cnf instead of directly on py-aiger.

pysat/formula.py
Set the number of variables attribute `CNF.nv` by computing the maximum literal seen in the clauses.
This is done by:
1. flattening the clauses using `itertools.chain`
2. taking the absolute value of each literal with `map(abs, ...)`
3. taking the `max` of the resulting sequence.
Addresses issue brought up in #21 .
=> From aiger count nv

setup.py
`py-aiger` and associated libraries require `python-3.6+`. `pysat` currently already treats `aiger` as an optional dependency, so this PR makes this explicit by introducing an `aiger` option to `setup.py`.
To install without `aiger` one would use:
`$ pip install python-sat`
To install with `aiger` one would use:
`$ pip install python-sat[aiger]`
=> Mark py-aiger-cnf as optional dependency

pysat/formula.py
If the package `aiger_cnf` is not found, it throws `ImportError` instead of `SyntaxError` in both python 2 and 3.
I think `SyntaxError` occurs while importing only when the source of the imported package has syntax error?
CC: @alexeyignatiev @mvcisback
=> fix(formula.py): catching aiger_cnf not found error

setup.py, zlib/zconf.h
I need one additional file (zconf.h) and a changed library setting for some Windows builds.
I also tested on Python 3.8 (on Windows).:
Here rc uses the no longer supported time.clock(). You might need timeit.default_timer() instead.
I have attached the .whl files for Python 3.7 and Python 3.8
[pypblib-whl.zip](https://github.com/pysathq/pysat/files/3923247/pypblib-whl.zip)
[pysat-whl.zip](https://github.com/pysathq/pysat/files/3923253/pysat-whl.zip)
=> Missing zconf.h added. Libraries for Windows build corrected.

pysat/solvers.py, solvers/pysolvers.cc
This adds a function accum_stats, which gets various low-level stats from the solver.
At the moment I've only added it for glucose41. I'm happy to add it for other solvers, but I thought I'd check if there were any general issues before duplicating the code for every solver.
I expect the exact list of stats to be different between solvers, but there will be common elements.
=> Add initial accum_stats, for glucose41

solvers/pysolvers.cc
Number of propagation for hard instances can be greater than max value of int32.
I have fixed string format in Py_BuildValue() function for all solvers.
=> Changed int32 to int64 for accum_stats

pysat/solvers.py
`.enum_models()` didn't distinguish between `[]` and `None`. That made it exit early instead of yielding `[]` as a model when solving an empty formula.
(MapleSAT segfaults anyway when given an empty formula, but other solvers can handle it)
=> Distinguish between an empty model and no model in .enum_models()

pysat/formula.py
I noticed that the conversion to OPB was partly written to STDOUT instead of the output file. This PR proposes a fix.
=> :bug: fixes incorrect position of "file_pointer" in to_alien

pysat/formula.py
fix #98
If no explicit topw is provided in the preamble of a WCNF problem, topw is initialized as float('inf').
After all clauses have been read, an infinity topw is replaced by a calculated one, by summing all weights plus one.
=> Calculating implicit topw in WCNF.from_fp function

pysat/formula.py
The example section in the CNF docstring has some bugs, including invalid syntax, which would result in no clauses actually being added.
```python3
>>> from pysat.formula import CNF
>>> cnf1 = CNF()
>>> cnf1.from_string('p cnf 2 2\\n-1 2 0\\n1 -2 0')
>>> print(cnf1.clauses)
[]
>>> cnf2 = CNF(from_string='p cnf 3 3\\n-1 2 0\\n-2 3 0\\n-3 0\\n')
>>> print(cnf2.clauses)
[]
```
```python3
>>> from pysat.formula import CNF
>>> cnf1 = CNF()
>>> cnf1.from_string('p cnf 2 2\n-1 2 0\n1 -2 0')
>>> print(cnf1.clauses)
[[-1, 2], [1, -2]]
>>> cnf2 = CNF(from_string='p cnf 3 3\n-1 2 0\n-2 3 0\n-3 0\n')
>>> print(cnf2.clauses)
[[-1, 2], [-2, 3], [-3]]
```
There also seem to be similar problems in WCNF, but I am not familiar with weighted CNF and hard and soft and all that. Changing the input string also …
=> Fixed CNF from_string example bug

pysat/formula.py
I've added `__repr__` to all formula classes. Methods of all four CNF classes are based on ``to_dimacs``.
On the other hand, should there be an example and explanation of all the DIMACS formats in the class docstring? Currently, there are only `cnf+` and `wcnf+` examples and explanations, hence my confusion about all the weight stuff with `wcnf` with hard and soft clauses.
=> Formula enhancement: added repr and to_dimacs methods to formula classes

examples/rc2.py
This is a fix for 2 recently discovered bugs in RC2 related to the partial introduction of new lazy counter variables.
The fix is to introduce new lazy counter variables with their full weight (weight of the core there are the counters for) instead of only the weight of the core in which the previous counter variable appeared. This way, the counter variables always have the right coefficient in the rewritten objective and never need to be reactivated.
=> Fix bug in RC2 related to partial introduction of new counters

pysat/formula.py, tests/test_clausification.py
Neg clausify is broken, it returns itself as a clause but I don't think it should ever do that.
An example:
``` 
from pysat.formula import Atom, And, Or, Neg
f = Or(Atom(1), Neg(Atom(2)), Neg(Atom(2)))
print(list(f))
>>> [[-2], [-2], [1, -2, -2]]
```
This assume that all models contain -2, but [1, 2] is a valid model. (The correct clause should be only [1, -2, -2], without the [-2]).
I propose a fix where Neg clauses is always empty. An extra variable `clausified`  is used to avoid multiple clausify of the subformula.
=> Fix Neg clausify

pysat/formula.py
When the `cleanup` method is used on any context the default Atom for True and False are cleaned too.
```
from pysat.formula import Formula, PYSAT_FALSE, PYSAT_TRUE
print(PYSAT_FALSE, PYSAT_TRUE)
>>>F T
Formula.cleanup()
print(PYSAT_FALSE, PYSAT_TRUE)
>>>None None
```
In particulars this mess up the results of simplified:
```
from pysat.formula import Atom, Or, Neg, Formula
print(Or(Atom(1), Neg(Atom(1))).simplified())
>>>T
Formula.cleanup()
print(Or(Atom(1), Neg(Atom(1))).simplified())
>>>None
```
I propose a fix to explicitly exclude PYSAT_FALSE and PYSAT_TRUE from cleanup and to register the same object again in the new context.
=> Protect True and False Atom from .cleanup

pysat/formula.py
Hello, I propose a fix to `test_clausification` not passing after #167.
Currently on master vpool are not cleaned correctly after creating a CNF:
```
print(dict(Formula._vpool))
>>> {}
cnf = CNF(from_clauses=[[1, 2, 3]])
print(dict(Formula._vpool))
>>> {'default': IDPool(start_from=1, occupied=[[1, 3]])}
Formula.cleanup()
print(dict(Formula._vpool))
>>> {'default': IDPool(start_from=1, occupied=[[1, 3]])}
```
It is because `Formula.cleanup` only looks at context within `_instances` and not at context in `._vpool`. 
It is possible to have a context in `_vpool` without being in `_instances` (ex: creating a CNF).
It is also possible to have a context in `_instances` without being in `_vpool` (ex: creating Atom(int)).
The bug didn't appear before because `'default'` context was always in …
=> Fix cleanup and CNF vpool updating

pysat/formula.py
There's a missing colon in the `pysat.formula` module docstring, causing the `Implies` class to be rendered incorrectly:
This PR fixes this by adding the missing colon.
=> docs(formula): fix rendering of the `Implies` class in the `pysat.formula` module docstring

tests/test_cnf.py
tests/test_cnfplus.py was testing both CNF and CNFPlus formulas, so its likely best to name it after the ancestor that's being used. As well, the individual tests were testing something far more complex than just the class itself. I've renamed them to something that begins to make sense for that they are.
=> Rename cnf tests

tests/test_cnf.py
Copying a new empty CNF should not raise an exception.
=> Add simple tests of CNF behaviour (construction, copy)

pysat/solvers.py, solvers/pysolvers.cc
See #83.
This is a proof of concept, currently limited to Glucose42. Support for other MiniSat-based solvers should be straightforward.
=> Extend Glucose42 API with randomness support
